// <auto-generated />
using System;
using AutoKassa.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoKassa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222230258_AddPaymentTypeAndCategoryColor")]
    partial class AddPaymentTypeAndCategoryColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("AutoKassa.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoBackupDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoGenerateReports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoLockEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoLockTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BackupKeepCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfirmDelete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomSecurityQuestion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultExpenseCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultIncomeCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultOperationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPageSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultPeriodFilter")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordExpireDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequirePasswordOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityAnswerHash")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SecurityQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowOperationsInSidebar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("WindowHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("WindowWidth")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoBackupDays = 7,
                            AutoGenerateReports = false,
                            AutoLockEnabled = true,
                            AutoLockTimeout = 10,
                            BackupEnabled = false,
                            BackupFrequency = "Weekly",
                            BackupKeepCount = 10,
                            ConfirmDelete = true,
                            DefaultOperationType = 2,
                            DefaultPageSize = 20,
                            DefaultPeriodFilter = "Month",
                            Language = "ru-RU",
                            PasswordExpireDays = 0,
                            PasswordHash = "",
                            RequirePasswordOnStartup = true,
                            ShowNotifications = true,
                            ShowOperationsInSidebar = false,
                            Theme = "Light",
                            WindowHeight = 700.0,
                            WindowWidth = 1200.0
                        });
                });

            modelBuilder.Entity("AutoKassa.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Category_IsActive");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Category_Type");

                    b.HasIndex("Name", "Type")
                        .IsUnique()
                        .HasDatabaseName("UQ_Category_Name_Type");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#6366f1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Ремонт авто",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#f59e0b",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Ремонт мото",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#14b8a6",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Диагностика",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Color = "#94a3b8",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Прочие доходы",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Color = "#ec4899",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Запчасти",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Color = "#f97316",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Зарплата",
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Color = "#8b5cf6",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Аренда",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Color = "#06b6d4",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Коммунальные услуги",
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Color = "#84cc16",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Маркетинг",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Color = "#ef4444",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Прочие расходы",
                            Type = 2
                        });
                });

            modelBuilder.Entity("AutoKassa.Models.FavoriteReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FavoriteReports");
                });

            modelBuilder.Entity("AutoKassa.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Transaction_CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Transaction_Date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Transaction_IsDeleted");

                    b.HasIndex("PaymentType")
                        .HasDatabaseName("IX_Transaction_PaymentType");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Transaction_Type");

                    b.HasIndex("Date", "IsDeleted")
                        .HasDatabaseName("IX_Transaction_Date_IsDeleted");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AutoKassa.Models.Transaction", b =>
                {
                    b.HasOne("AutoKassa.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoKassa.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
